version: '3.8'

services:
  focusflow-app:
    image: node:20-alpine
    container_name: focusflow2-ci
    working_dir: /app
    volumes:
      - .:/app 
    ports:
      - "4000:3000" 
    environment:
      - MONGODB_URI=mongodb+srv://nayabkhalid13:sprinkles2017@focusflow.rqb31jj.mongodb.net/focusflow?retryWrites=true&w=majority&appName=FocusFlow
      - NODE_ENV=development 
    command: >
      sh -c "npm install @tailwindcss/postcss postcss && npm install && npm run dev -- -p 3000"
